# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  extract-and-set-variables:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up environment variables
      run: |
        $filePath = "variables.txt"
        $keyValuePairs = Get-Content $filePath | ConvertFrom-StringData
        $keyValuePairs.GetEnumerator() | ForEach-Object {
          $name = $_.Name
          $value = $_.Value
          Write-Host "Setting environment variable: $name=$value"
          $env:$name = $value
        }
        
    - name: Print environment variables
      run: |
        Get-ChildItem Env: | Sort-Object Name | Format-Table Name, Value
